page:
  width: 1200
  height: 800
  background: "#ffffff"

shape:
  header:
    style: "rounded=1;fillColor=#dae8fc"
    width: 140
    height: 40
  subheader:
    style: "rounded=1;fillColor=#d5e8d4"
    width: 120
    height: 30
  item:
    style: "rounded=1;fillColor=#fff2cc"
    width: 100
    height: 25

layout:
  header_x: 500
  header_y: 50
  subheader_spacing_y: 120
  item_spacing_x: 180
  item_spacing_y: 35
