page:
  width: 800
  height: 600
  background: "#ffffff"

shape:
  header:
    style: "rounded=1;fillColor=#dae8fc"
    width: 120
    height: 40
  subheader:
    style: "rounded=1;fillColor=#d5e8d4"
    width: 100
    height: 30
  item:
    style: "rounded=1;fillColor=#fff2cc"
    width: 80
    height: 25
